[window]
padding = { x = 10, y = 10}
opacity = 0.8
blur = true

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 13

[selection]
save_to_clipboard = true

[cursor]
style = {shape="Beam",blinking="On"}


