alias ls='ls --color=auto'
alias l='ls -la'
alias ld='ls -lDa'
alias grep='grep --color=auto'
alias add='sudo pacman -S'
alias remove='sudo pacman -Rns'
alias search='sudo pacman -Ss'
alias programs='sudo pacman -Qe'
alias hyprconf='nvim ~/.config/hypr/hyprland.conf'
alias c='clear'
alias gc='git commit'
alias gp='git pull'
alias ga='git add'
alias mount='mount |column -t'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'